# Generated by Django 3.2.9 on 2022-03-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_typeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='typeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.typeproduct'),
            preserve_default=False,
        ),
    ]
